# Site settings
title: Catfish
tagline: Tiger's home
email: shenghuATnjuDOTeduDOTcom
description: > # this means to ignore newlines until "baseurl:"
  R is the brush, math is the pigment, nature is the scenery, and science is the picture.
url: "https://ctfysh.github.io" # the base hostname & protocol for your site
github_username:  ctfysh
permalink: /:year/:month/:day/:title.html
# highlighter:  rouge (on my Mac, need to set this to rouge or flas with Jekyll 3.0)
author:  Tiger

baseurl: "/" # the sub-path of your proejct site, e.g. /myProject/
             # or "/" for user site

# limit posts on Home page to this number:
homepostlimit:  4

# Disqus comments:
disqus:           false
shortname:        ctfysh

# Social Media
twitter:          false # add a twitter button to each post
facebook:         false # add a facebook share button to each post

# Build settings

# rendering engine
markdown: kramdown

author:
  name:           'Tiger'
  url:            http://www.njumce.com/

github:
  repo:           https://github.com/ctfysh/ctfysh.github.io
